# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
  

default: &default
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 100
  username: esns
  port: 3306
  host: 127.0.0.1

development:
  <<: *default
  database: esns_development
  password: minxing123


production:
  <<: *default
  database: esns_production
  password: esns
